name: Remove PR Labels

on:
  pull_request_target:
    types: ["closed", "merged"]

jobs:
  remove_label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0  # v1
      with:
        labels: |
          status:awaiting review
          status:awaiting user response
