name: Remove issue labels

on:
  issues:
    types: [closed]

jobs:
  remove_label:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0  # v1
      with:
        labels: |
          status:triaged
          status:more data needed
